version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:80"
    container_name: simple-html-site
    restart: unless-stopped
    volumes:
      - .:/usr/share/nginx/html:ro  # Mount current directory to Nginx html directory in read-only mode